name: llm_ai_modelling
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.2
  - aiosignal=1.3.1
  - appnope=0.1.4
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=24.2.0
  - aws-c-auth=0.7.31
  - aws-c-cal=0.7.4
  - aws-c-common=0.9.28
  - aws-c-compression=0.2.19
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.10
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.6
  - aws-c-s3=0.6.6
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.20
  - aws-crt-cpp=0.28.3
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - datasets=3.0.1
  - debugpy=1.8.6
  - decorator=5.1.1
  - dill=0.3.8
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.16.1
  - frozenlist=1.4.1
  - fsspec=2024.6.1
  - gflags=2.2.2
  - glog=0.7.1
  - h2=4.1.0
  - hpack=4.0.0
  - huggingface_hub=0.25.1
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libabseil=20240116.2
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libcxx=19.1.0
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.29.0
  - libgoogle-cloud-storage=2.29.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libparquet=17.0.0
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.20
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libthrift=0.20.0
  - libutf8proc=2.8.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - mlx=0.7.0
  - mlx-lm=0.4.0
  - multidict=6.1.0
  - multiprocess=0.70.16
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openssl=3.3.2
  - orc=2.0.2
  - packaging=24.1
  - pandas=2.2.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow-core=17.0.0
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.10.15
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.9.11
  - requests=2.32.3
  - safetensors=0.4.5
  - setuptools=75.1.0
  - six=1.16.0
  - snappy=1.2.1
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==0.34.2
      - ace-tools-open==0.1.0
      - aiohttp==3.10.7
      - alembic==1.13.3
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.0
      - asteroid-filterbanks==0.4.0
      - audioread==3.0.1
      - backtesting==0.6.4
      - beautifulsoup4==4.13.3
      - binance==0.3.80
      - bitsandbytes==0.42.0
      - bleach==6.2.0
      - bokeh==3.7.3
      - clarabel==0.11.1
      - click==8.1.7
      - colorlog==6.8.2
      - contourpy==1.3.0
      - curl-cffi==0.12.0
      - cvxpy==1.7.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - dateparser==1.2.2
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - docstring-parser==0.16
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - fastjsonschema==2.21.1
      - fonttools==4.54.1
      - frozendict==2.4.6
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - hyperpyyaml==1.2.2
      - insanely-fast-whisper==0.0.15
      - itables==2.5.2
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - julius==0.2.7
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.7
      - langchain==0.3.1
      - langchain-community==0.3.1
      - langchain-core==0.3.6
      - langchain-ollama==0.2.0
      - langchain-text-splitters==0.3.0
      - langsmith==0.1.129
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - lightning==2.4.0
      - lightning-utilities==0.11.7
      - llvmlite==0.43.0
      - lxml==6.0.2
      - mako==1.3.5
      - markdown-it-py==3.0.0
      - marshmallow==3.22.0
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mistune==3.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multitasking==0.0.12
      - mypy-extensions==1.0.0
      - narwhals==2.0.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.3
      - numba==0.60.0
      - ollama==0.3.3
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - optuna==4.0.0
      - orjson==3.10.7
      - osqp==1.0.5
      - pandocfilters==1.5.1
      - patsy==1.0.2
      - peewee==3.18.2
      - peft==0.13.0
      - pillow==10.4.0
      - plotly==6.2.0
      - pooch==1.8.2
      - primepy==1.3
      - protobuf==5.28.2
      - py3langid==0.3.0
      - pyannote-audio==3.3.2
      - pyannote-core==5.0.0
      - pyannote-database==5.1.0
      - pyannote-metrics==3.2.1
      - pyannote-pipeline==3.0.1
      - pyarrow==17.0.0
      - pycryptodome==3.23.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.5.2
      - pyparsing==3.1.4
      - python-binance==1.0.31
      - python-dotenv==1.0.1
      - pytorch-lightning==2.4.0
      - pytorch-metric-learning==2.6.0
      - pytz==2024.2
      - referencing==0.36.2
      - rich==13.8.1
      - rpds-py==0.23.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - scs==3.2.9
      - seaborn==0.13.2
      - semver==3.0.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.14.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shtab==1.7.1
      - simfin==1.0.1
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soupsieve==2.6
      - soxr==0.5.0.post1
      - speechbrain==1.0.1
      - sqlalchemy==2.0.35
      - statsmodels==0.14.5
      - sympy==1.13.3
      - ta==0.11.0
      - tabulate==0.9.0
      - tenacity==8.5.0
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tinycss2==1.4.0
      - tokenizers==0.20.0
      - torch==2.2.2
      - torch-audiomentations==0.11.1
      - torch-pitch-shift==1.2.5
      - torchaudio==2.2.2
      - torchmetrics==1.4.2
      - transformers==4.45.1
      - trl==0.11.1
      - typer==0.12.5
      - typing-inspect==0.9.0
      - tyro==0.8.11
      - tzlocal==5.3.1
      - unsloth==2024.8
      - wandb==0.18.2
      - webencodings==0.5.1
      - websockets==15.0.1
      - xlsxwriter==3.2.5
      - xyzservices==2025.4.0
      - yarl==1.13.1
      - yfinance==0.2.65
prefix: /Users/kevintanyuejun/opt/anaconda3/envs/llm_ai_modelling
